# Generated by Django 5.1.5 on 2025-01-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_userprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=10,
                null=True,
            ),
        ),
    ]
