# Generated by Django 5.1.5 on 2025-01-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_userprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodgroup",
            name="category",
            field=models.CharField(
                choices=[
                    ("carbohydrates", "Carbohydrates"),
                    ("proteins", "Proteins"),
                    ("vitamins", "Vitamins"),
                ],
                default="carbohydrates",
                max_length=50,
            ),
        ),
    ]
