# Generated by Django 5.1.5 on 2025-01-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_foodgroup_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nutritionlog",
            name="food_group",
        ),
        migrations.AddField(
            model_name="nutritionlog",
            name="food_group",
            field=models.ManyToManyField(to="tracker.foodgroup"),
        ),
    ]
