# Generated by Django 5.1.5 on 2025-01-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_remove_nutritionlog_food_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodgroup",
            name="category",
            field=models.CharField(
                choices=[
                    ("carbohydrates", "Carbohydrates"),
                    ("proteins", "Proteins"),
                    ("vitamins", "Vitamins"),
                ],
                max_length=50,
            ),
        ),
    ]
