# Generated by Django 5.1.5 on 2025-01-24 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0007_alter_foodgroup_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Protein", "Protein"),
                            ("Carbohydrate", "Carbohydrate"),
                            ("Vitamin", "Vitamin"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="foodgroup",
            name="category",
        ),
        migrations.AlterField(
            model_name="foodgroup",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="foodgroup",
            name="categories",
            field=models.ManyToManyField(
                related_name="food_groups", to="tracker.category"
            ),
        ),
        migrations.CreateModel(
            name="Nutrition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_item", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="nutritions", to="tracker.category"
                    ),
                ),
                (
                    "food_group",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracker.foodgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="NutritionLog",
        ),
    ]
