# Generated by Django 5.1.5 on 2025-01-24 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_category_remove_foodgroup_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutrition",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
